name: Continuous Deployment (CD)

on:
  workflow_run:
    workflows: ["Continuous Integration (CI)", "SonarCloud"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Koyeb CLI
      run: |
        curl -sL https://deb.koyeb.com/install.sh | bash
        koyeb auth login --token ${{ secrets.KOYEB_API_TOKEN }}

    - name: Deploy to Koyeb
      run: |
        koyeb service redeploy papikos-be --app papikos-a15