name: Continuous Deployment (CD)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Koyeb CLI v5.5.0
      run: |
        curl -LO https://github.com/koyeb/koyeb-cli/releases/download/v5.5.0/koyeb-cli_5.5.0_linux_amd64.tar.gz
        tar -xzf koyeb-cli_5.5.0_linux_amd64.tar.gz
        sudo mv koyeb-cli /usr/local/bin/koyeb
        koyeb version

    - name: Log in to Koyeb
      run: koyeb auth login --token ${{ secrets.KOYEB_API_TOKEN }}

    - name: Deploy to Koyeb
      run: koyeb service redeploy papikos-be --app papikos-a15