name: Continuous Deployment (CD)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Koyeb CLI from GitHub Release
      run: |
        curl -LO https://github.com/koyeb/koyeb-cli/releases/latest/download/koyeb-linux.tgz
        tar -xzf koyeb-linux.tgz
        sudo mv koyeb /usr/local/bin
        koyeb version

    - name: Log in to Koyeb
      run: koyeb auth login --token ${{ secrets.KOYEB_API_TOKEN }}

    - name: Deploy to Koyeb
      run: koyeb service redeploy papikos-be --app papikos-a15