name: Test and Deploy

on:
  push:
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  scorecard:
    uses: ./.github/workflows/scorecard.yml

  sonarcloud:
    uses: ./.github/workflows/sonarcloud.yml

  deploy:
    needs: [ci, scorecard, sonarcloud]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Koyeb CLI and login
        run: |
          curl -sL https://deb.koyeb.com/install.sh | bash
          koyeb auth login --token ${{ secrets.KOYEB_API_TOKEN }}

      - name: Redeploy to Koyeb
        run: |
          koyeb service redeploy papikos-be --app papikos-a15